// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;
float height;
RWStructuredBuffer<int> buffer;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    int location = id.x * height + id.y;
    int c = buffer.Load(location);

    Result[id.xy] = float4(c,0,0,0);

    // TODO: insert actual code here!
}
